server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    dialect: postgres
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
    host: 0.0.0.0
    port: 5432
    name: "commondb"
    username: "test"
    password: "test"
    sslmode: disable

