// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package common

import (
	"common-inv/internal/biz"
	"common-inv/internal/conf"
	"common-inv/internal/data"
	"common-inv/internal/server"
	"common-inv/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	clusterRepo := data.NewClusterRepo(dataData, logger)
	clusterUsecase := biz.NewClusterUsecase(clusterRepo, logger)
	clusterService := service.NewClusterServiceService(clusterUsecase)
	grpcServer := server.NewGRPCServer(confServer, clusterService, logger)
	httpServer := server.NewHTTPServer(confServer, clusterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
